//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentTable
    {
        public int CommentId { get; set; }
        public string CommentText { get; set; }
    }
}
